"""Initial migration

Revision ID: a9238e2e2596
Revises: 
Create Date: 2026-02-11 13:36:34.261152

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a9238e2e2596"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
